name: 🐛 Bug Report
description: Report a bug or unexpected behavior in Insight Ingenious
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form as completely as possible.
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the issue
      placeholder: |
        1. Run command: `uv run ingen ...`
        2. Send request to: `curl -X POST ...`
        3. See error...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: What should have happened instead?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: What actually happened?
    validations:
      required: true
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Multi-Agent Framework
        - Configuration System
        - API Endpoints
        - Chainlit Web UI
        - Azure Services Integration
        - Database/Storage
        - Documentation
        - CLI Tools
        - Extensions/Templates
        - Other
    validations:
      required: true
  - type: dropdown
    id: workflow
    attributes:
      label: Affected Workflow
      description: Which conversation workflow is affected (if applicable)?
      options:
        - Not applicable
        - classification_agent
        - knowledge_base_agent
        - sql_manipulation_agent
        - bike_insights
        - document-processing
        - Custom workflow
        - All workflows
  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Please provide details about your environment
      placeholder: |
        - OS: [e.g., Windows 10, macOS 13, Ubuntu 22.04]
        - Python version: [e.g., 3.13.1]
        - uv version: [run `uv --version`]
        - Insight Ingenious version: [e.g., 0.1.0]
        - Azure services used: [e.g., Azure OpenAI, Azure Search]
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Configuration Details
      description: Relevant configuration settings (remove sensitive information like API keys)
      placeholder: |
        config.yml relevant sections:
        ```yaml
        # Paste relevant config here
        ```

        profiles.yml structure (no sensitive data):
        ```yaml
        # Paste structure only, no API keys
        ```
  - type: textarea
    id: logs
    attributes:
      label: Error Logs/Output
      description: Any relevant error messages or logs
      placeholder: |
        ```
        Paste error messages or logs here
        ```
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have removed any sensitive information (API keys, credentials) from this report
          required: true
        - label: I have included relevant configuration and environment details
          required: true
