name: 📚 Documentation Improvement
description: Suggest improvements to documentation or report documentation issues
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation! Report issues or suggest improvements to make Insight Ingenious easier to understand and use.
  - type: dropdown
    id: doc_type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - README.md
        - Getting Started guide
        - Configuration documentation
        - API documentation
        - Workflow documentation
        - Development/Contributing guide
        - Extension/Customization guide
        - Code comments/docstrings
        - Example code/tutorials
        - Error messages/help text
    validations:
      required: true
  - type: textarea
    id: issue_description
    attributes:
      label: Issue Description
      description: Describe the documentation issue or improvement needed
      placeholder: |
        What's wrong with the current documentation or what improvement would you like to see?
        For example:
        - Information is missing or unclear
        - Examples don't work
        - Instructions are out of date
        - Need more detailed explanations
        - Typos or formatting issues
    validations:
      required: true
  - type: textarea
    id: current_content
    attributes:
      label: Current Content (if applicable)
      description: Quote or reference the current documentation content that needs improvement
      placeholder: |
        If you're referring to specific existing content, please quote it here or provide a link to the section.
  - type: textarea
    id: suggested_improvement
    attributes:
      label: Suggested Improvement
      description: What would you like to see instead?
      placeholder: |
        Describe your suggested improvement or provide better wording/examples.
        If you have specific text to suggest, please include it.
  - type: textarea
    id: location
    attributes:
      label: File/Location
      description: Which file or section needs improvement?
      placeholder: |
        For example:
        - docs/getting-started/README.md
        - README.md line 45
        - docs/configuration/README.md
        - API docstring in ingenious/api/chat.py
    validations:
      required: true
  - type: dropdown
    id: audience
    attributes:
      label: Target Audience
      description: Who is the primary audience for this documentation?
      options:
        - New users/beginners
        - Developers/contributors
        - System administrators/DevOps
        - API users/integrators
        - Extension developers
        - All users
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this documentation improvement?
      options:
        - Low - Minor improvement
        - Medium - Would help user experience
        - High - Important for usability
        - Critical - Blocking user adoption
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any additional context about why this improvement is needed
      placeholder: |
        For example:
        - "I spent hours trying to figure this out"
        - "Multiple users have asked about this in discussions"
        - "This caused issues during deployment"
        - "The current example doesn't work with latest Azure services"
  - type: checkboxes
    id: improvement_type
    attributes:
      label: Type of Improvement
      description: What kind of improvement is this? (Select all that apply)
      options:
        - label: Fix incorrect information
        - label: Add missing information
        - label: Improve clarity/readability
        - label: Add examples or tutorials
        - label: Fix typos or formatting
        - label: Update outdated information
        - label: Improve organization/structure
        - label: Add troubleshooting information
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have clearly identified the location of the documentation issue
          required: true
        - label: I have provided constructive suggestions for improvement
          required: true
